name               = "my-cloudflare-site"
account_id         = "14980bb23a816af094ebf37c54c768ab"
compatibility_date = "2025-05-28"
compatibility_flags = []
workers_dev        = true
main               = "src/index.js"

[build]
command = ""

# D1 바인딩
[[d1_databases]]
binding        = "COINGECKO_DB"
database_id    = "c1cb676c-7f7a-40c3-b271-cd007f65bfbc"
database_name  = "my_coingecko_db"

# R2 바인딩
[[r2_buckets]]
binding     = "CHARTS"
bucket_name = "my-chart-bucket"

[triggers]
crons = ["0 * * * *"]
