name               = "my-coingecko-worker"
account_id         = "14980bb23a816af094ebf37c54c768ab"
compatibility_date = "2025-05-26"
workers_dev        = true

# 여기를 src/index.js 로 바꿔 주세요!
main = "src/index.js"
type = "javascript"

[[d1_databases]]
binding       = "COINGECKO_DB"
database_id   = "c1cb676c-7f7a-40c3-b271-cd007f65bfbc"
database_name = "my_coingecko_db"

[triggers]
crons = ["0 * * * *"]
