name               = "my-cloudflare-site"
account_id         = "14980bb23a816af094ebf37c54c768ab"
compatibility_date = "2025-05-28"
workers_dev        = true
main               = "src/index.js"

# D1 바인딩 (database_id를 반드시 지정)
[[d1_databases]]
binding        = "COINGECKO_DB"
database_id    = "c1cb676c-7f7a-40c3-b271-cd007f65bfbc"  # ← 여기에 실제 D1 인스턴스 ID
database_name  = "my_coingecko_db"

# R2 바인딩
[[r2_buckets]]
binding     = "CHARTS"
bucket_name = "my-chart-bucket"

[triggers]
crons = ["0 * * * *"]
